app.controller("galleryCtrl",function($scope){
   $scope.photos = [{src:"image/traditional/traditional.jpg", title:"traditional-art tag"},
                 {src:"image/traditional/dragon.jpg", title:"dragon sketch"},
                 {src:"image/traditional/dragon1.jpg", title:"dragon sketch"},
                 {src:"image/traditional/dragon2.jpg", title:"dragon sketch"},
                 {src:"image/traditional/dragon3.jpg", title:"dragon sketch"},
                 {src:"image/traditional/flamingo.jpg", title:"One Piece Doo Flamingo"},
                 {src:"image/traditional/four.JPG", title:"One Piece four"},
                 {src:"image/traditional/hancock.JPG", title:"One Piece Hancock"},
                 {src:"image/traditional/law.jpg", title:"One Piece Law"},
                 {src:"image/traditional/luffy.JPG", title:"One Piece Luffy"},
                 {src:"image/traditional/nami.JPG", title:"One Piece Nami"},
                 {src:"image/traditional/nami1.JPG", title:"One Piece Nami"},
                 {src:"image/traditional/robin.JPG", title:"One Piece Robin"},
                 {src:"image/traditional/robin1.JPG", title:"One Piece Robin"},
                 {src:"image/traditional/robin2.JPG", title:"One Piece Robin"},
                 {src:"image/traditional/sanji.JPG", title:"One Piece Sanji"},
                 {src:"image/traditional/ship.JPG", title:"One Piece Ship"},
                 {src:"image/traditional/three.JPG", title:"One Piece three"},
                 {src:"image/traditional/three1.JPG", title:"One Piece three"},
                 {src:"image/traditional/zoro.JPG", title:"One Piece Zoro"},
                 {src:"image/traditional/zoro1.JPG", title:"One Piece Zoro"},
                 {src:"image/digital/digital.jpg", title:"digital-art tag"},
                 {src:"image/digital/background1.jpg", title:"untitle"},
                 {src:"image/digital/digital1.jpg", title:"OnePiece Perona & Sanji"},
                 {src:"image/digital/digital2.jpg", title:"Tokyo Ghoul Donka"},
                 {src:"image/digital/digital3.jpg", title:"Dragon Fire"},
                 {src:"image/digital/digital4.jpg", title:"Child Nami"},
                 {src:"image/digital/digital5.jpg", title:"Tokyo Ghoul Donka V2"},
                 {src:"image/digital/digital6.jpg", title:"Thunder Dragon"},
                 {src:"image/digital/digital7.jpg", title:"OP Nami"},
                 {src:"image/digital/digital8.jpg", title:"Digimon"},
                 {src:"image/digital/digital9.jpg", title:"Child Hancock"},
                 {src:"image/photoshop/photoshop.jpg", title:"Photoshop Tag"},
                 {src:"image/photoshop/girl-ps.jpg", title:"Girl After PS"},
                 {src:"image/photoshop/hotday.jpg", title:"Really hot afternoon"},
                 {src:"image/photoshop/MM.jpg", title:"M&M cross the road"},
                 {src:"image/photoshop/wierd animal.jpg", title:"Wierd animal"},
                 {src:"image/photograph/photograph.jpg", title:"Photograph Tag"},
                 {src:"image/photograph/photograph1.JPG", title:"GREEK VIEW"},
                 {src:"image/photograph/photograph2.JPG", title:"GREEK VIEW"},
                 {src:"image/photograph/photograph3.JPG", title:"GREEK VIEW"},
                 {src:"image/photograph/photograph4.JPG", title:"WASHINGTON, DC"},
                 {src:"image/photograph/photograph5.JPG", title:"WASHINGTON, DC"},
                 {src:"image/photograph/photograph6.JPG", title:"Car Show"}
   ];

});